"""Generate an arXiv-safe label-snapshot file from a document's .aux.

Replaces \\externaldocument[PREFIX-]{doc}[doc.pdf] (xr-hyper), which cannot
work on arXiv because the submission pipeline deletes .aux files. The
snapshot inlines every \\newlabel from the other document's final local
.aux, with the requested prefix applied, and with the nameref-text field
(3rd top-level group of 5-field hyperref payloads) blanked -- the same
sanitization sanitize_aux.py applies, which is ALSO required to keep
modern xr-hyper (v7.00n, TeX Live 2022+) from crashing with "Undefined
control sequence" on document macros (e.g. \\hatg) inside caption text.

The 5th field (external-file URL) is set to the other document's PDF
name, which is exactly what xr-hyper stores when given
\\externaldocument[PREFIX-]{doc}[doc.pdf] -- so \\ref/\\cref hyperlinks
keep pointing at the sibling PDF, byte-for-byte the current behavior.

cleveref's "label@cref" companion entries (2-field payloads) are copied
with the prefix applied and payload untouched, so \\cref{PREFIX-label}
keeps working.

Usage: python gen_xr_labels.py <other.aux> <PREFIX-> <out.tex> <url.pdf>
"""
import sys


def groups(s, start):
    """Top-level {...} spans starting at s[start] == '{'."""
    out = []
    i = start
    n = len(s)
    while i < n and s[i] == '{':
        depth = 0
        j = i
        while j < n:
            c = s[j]
            if c == '{':
                depth += 1
            elif c == '}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        if depth != 0:
            return None
        out.append((i, j))
        i = j + 1
    return out


def convert(aux_path, prefix, out_path, url):
    tag = '\\newlabel{'
    kept, skipped = 0, 0
    lines_out = []
    with open(aux_path, 'r', encoding='latin-1', newline='') as f:
        for line in f:
            line = line.rstrip('\r\n')
            if not line.startswith(tag):
                continue
            g = groups(line, len(tag) - 1)
            if not g or len(g) < 2:
                skipped += 1
                continue
            (nb, ne), (pb, pe) = g[0], g[1]
            name = line[nb + 1:ne]
            payload = line[pb:pe + 1]
            inner = groups(line, pb + 1)
            # 5-field hyperref payload: blank nameref text (3rd field),
            # set external URL (5th field) like xr-hyper would.
            if inner and len(inner) >= 5 and not name.endswith('@cref'):
                fields = [line[b + 1:e] for (b, e) in inner]
                fields[2] = ''
                fields[4] = url
                payload = '{' + ''.join('{%s}' % x for x in fields) + '}'
            lines_out.append('\\newlabel{%s%s}%s' % (prefix, name, payload))
            kept += 1
    with open(out_path, 'w', encoding='latin-1', newline='\n') as f:
        f.write('%% Auto-generated by gen_xr_labels.py from %s\n' % aux_path)
        f.write('%% arXiv-safe replacement for xr-hyper \\externaldocument'
                '[%s]{...}: arXiv deletes .aux files,\n' % prefix)
        f.write('%% so external labels are inlined here. '
                'Regenerate after any label change.\n')
        f.write('\\makeatletter\n')
        f.write('\n'.join(lines_out))
        f.write('\n\\makeatother\n')
    print('%s -> %s: %d labels (prefix %r), %d skipped'
          % (aux_path, out_path, kept, prefix, skipped))


if __name__ == '__main__':
    convert(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
