"""Transient demo: photon-kick response of ``f(E, t)``.

Start at thermal equilibrium at ``T_B = 0.1 K``, turn on a
pair-breaking photon drive at ``t = 0``, and evolve ``f(E)`` under
the collision operator with ``n_ph`` frozen at the bath
Bose-Einstein. The time series shows ``f(E)`` climbing from the
thermal floor up to the driven steady state as pair breaking builds
a non-equilibrium QP population.

Uses the :func:`qpsim.services.transient.run_time_dependent` driver
from Gate 3 — the companion to the nbar-loop and steady-state
services that provides transient capability for the v1 T3 backend.

Parameters (Fischer 2024 Sec. IV pair-breaking configuration):

    Δ₀      = 189 μeV
    τ_0     = 63 ns
    T_B     = 0.1 K
    ω_PB    = 2.8 Δ₀
    c·n̄     = 1e-3 ns⁻¹   (strong drive — visible transient)

Grid: 810 bins so ω_PB/dE = 252 is integer-commensurate. Total
evolution time 120 ns at dt = 0.1 ns captures both the e-ph
relaxation (τ_0 = 63 ns) and the drive ramp-up to its steady state.

Produces a two-panel figure: ``f(E)`` snapshots overlaid on the
driven steady state (upper) and ``x_qp(t)`` trajectory (lower).

Usage::

    python -m validation.transient.photon_kick_response
"""

from __future__ import annotations

import csv
import hashlib
import json
import os
import platform
import re
import sys
import zlib
from collections.abc import Iterator, Mapping
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Any

import numpy as np
from qpsim.backends.t3_diffusion import T3DiffusionBackend, T3DiffusionState
from qpsim.collisions.pair_breaking_photon import (
    pair_breaking_photon_collision_components,
)
from qpsim.collisions.phonon import (
    build_phonon_frequency_map,
    build_recombination_kernel_base,
    build_scattering_kernel_base,
    phonon_collision_rates,
)
from qpsim.constants import KB_UEV_PER_K
from qpsim.grid.energy_grid import build_energy_grid, integration_widths_from_centers
from qpsim.materials.database import Material
from qpsim.observables.density import qp_fraction
from qpsim.phonon_models.state import PhononBranchSpec, PhononModel, PhononState
from qpsim.physics.kernels import thermal_phonon_occupation
from qpsim.physics.spectral import SpectralContext, fermi_dirac_occupation
from qpsim.services.transient import run_time_dependent

from validation.source_provenance import source_manifest

# ── Fischer 2024 Sec. IV parameters (pair-breaking photon drive) ────
DELTA_0 = 189.0
TAU_0 = 63.0
T_C = DELTA_0 / (1.764 * KB_UEV_PER_K)
T_BATH = 0.1
OMEGA_PB = 2.8 * DELTA_0  # 529.2 μeV, above 2Δ → pair-breaking
N_BAR_PB = 1e6
C_PHOT_PB = 1e-9  # c·n̄ = 1e-3 ns⁻¹ (strong drive, visible transient)

E_MIN_FACTOR = 1.0
E_MAX_FACTOR = 10.0
NUM_BINS = 810  # ω_PB/dE = 252 integer commensurate

# Transient schedule.
DT = 0.1  # ns
TOTAL_TIME = 120.0  # ns  — resolves the τ_0 = 63 ns timescale
SNAPSHOT_INTERVAL = 6.0  # ns  →  21 snapshots including t=0

# Artifact provenance is intentionally embedded in both output formats.  The
# 2026-07-16 numerical-software audit replaced point-DOS midpoint collision
# quadrature with the matched finite-volume BCS capacity used by observables
# and ETD balance.  The canonical dt=0.1 ns trajectory was qualified against
# dt=0.2 and 0.05 ns runs before this pin was regenerated.
BASELINE_PROVENANCE = (
    "Historical qualification (2026-07-16 source): matched finite-volume BCS "
    "cell_weights/cell_density collision measure; adaptive-ETD dt=0.2/0.1/0.05 "
    "ns study bounded canonical 0.1-vs-0.05 differences by 2.56e-11 in f and "
    "5.89e-12 in x_qp. The current source-bound artifact authenticates the dt=0.1 "
    "trajectory but does not claim to have rerun that historical three-dt study."
)
PLOT_QUALIFICATION = (
    "qpsim source-bound regression at dt=0.1 ns\n"
    "Historical dt=0.2/0.1/0.05 ns refinement was not rerun for this artifact."
)

ARTIFACT_SCHEMA = "qpsim.transient.photon-kick-response.v4"

# The CSV stores sparse trajectory snapshots, not every internal ETD2 substep.
# Its reader can independently validate the state domain, thermal seed,
# monotone response, endpoint/steady-state proximity, x_qp reconstruction, and
# steady-state balance.  It cannot certify that the path between snapshots was
# generated by the transient integrator.  That stronger claim belongs to the
# slow live-recompute regression, which executes run() and compares the result.
TRAJECTORY_EVIDENCE_SCOPE = (
    "stored-snapshot-structure-and-endpoints-only;dynamics-certified-by-slow-live-recomputation"
)

STEADY_STATE_CERTIFICATE_METRIC = "thermal-pb-qp-l1-maxabs-pair-number-v1"
STEADY_STATE_CERTIFICATE_FIELDS = (
    "qp_backward_error",
    "qp_residual_inf",
    "qp_number_backward_error",
)
STEADY_STATE_BACKWARD_ERROR_LIMIT = 1.0e-6
STEADY_STATE_RESIDUAL_INF_LIMIT = 1.0e-10
STEADY_STATE_NUMBER_ERROR_LIMIT = 1.0e-6
# The certificate scalars are summaries of a freshly reassembled balance, not
# bitwise payload identities.  OpenBLAS reduction order changes the
# roundoff-limited L1 summaries slightly with its thread count: on the canonical
# 810-bin state, 1 versus 32 threads moved qp_backward_error by 4.5e-5 relative
# and qp_number_backward_error by 2.1e-4 relative while residual_inf and the
# persisted E/f arrays were unchanged.  Keep a narrow margin above that measured
# effect for stamp binding; _validated_steady_state_certificate() still applies
# every absolute physics gate independently to both the stamp and fresh result.
STEADY_STATE_CERTIFICATE_BINDING_RTOL = 1.0e-3
FINAL_X_QP_RELATIVE_GAP_LIMIT = 1.0e-2
FINAL_OCCUPATION_WEIGHTED_L1_LIMIT = 2.0e-2


class PhotonKickArtifactError(RuntimeError):
    """Raised when a transient artifact is incomplete, stale, or malformed."""


@dataclass(frozen=True)
class CompanionArtifactRecord:
    """Exact content identity for the PDF paired with the CSV commit marker."""

    sha256: str
    size_bytes: int


def solver_fingerprint() -> dict[str, Any]:
    """Return the portable source/configuration identity of this trajectory."""
    return {
        "schema": ARTIFACT_SCHEMA,
        "solver_config": {
            "Delta_0_uev": DELTA_0,
            "T_bath_K": T_BATH,
            "T_c_K": T_C,
            "c_phot_PB_per_ns": C_PHOT_PB,
            "dt_ns": DT,
            "energy_max_factor": E_MAX_FACTOR,
            "energy_min_factor": E_MIN_FACTOR,
            "n_bar_PB": N_BAR_PB,
            "newton_max_iter": 500,
            "newton_tol": 1.0e-14,
            "num_bins": NUM_BINS,
            "omega_PB_uev": OMEGA_PB,
            "snapshot_interval_ns": SNAPSHOT_INTERVAL,
            "tau_0_ns": TAU_0,
            "total_time_ns": TOTAL_TIME,
        },
        "source_sha256": source_manifest(Path(__file__)),
    }


def _canonical_json(value: Any) -> str:
    return json.dumps(
        value,
        allow_nan=False,
        separators=(",", ":"),
        sort_keys=True,
    )


_PDF_STARTXREF_RE = re.compile(rb"startxref[ \t\r\n]+(\d+)[ \t\r\n]+%%EOF[ \t\r\n]*\Z")
_PDF_REF_RE = re.compile(rb"(\d+)\s+(\d+)\s+R")
_PDF_SEMANTIC_MARK_RE = re.compile(
    rb"(?:\A|[\x00\t\n\f\r ])"
    rb"(?:S|s|B|B\*|b|b\*|Do|Tj|TJ)"
    rb"(?=\Z|[\x00\t\n\f\r ])"
)


def _classic_pdf_xref(payload: bytes, *, path: Path) -> dict[int, tuple[int, int]]:
    """Parse the classic cross-reference table emitted by Matplotlib.

    This is deliberately a strict parser for the producer contract, not a
    general-purpose PDF repair tool.  It rejects xref streams, incremental
    updates, missing object offsets, and trailing bytes after ``%%EOF``.
    Accepting only the format qpsim writes keeps this check dependency-free
    while still parsing page-tree and content-stream structure instead of
    trusting a ``%PDF`` prefix and an ``%%EOF`` substring.
    """
    match = _PDF_STARTXREF_RE.search(payload)
    if match is None:
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has no terminal PDF xref/EOF record."
        )
    xref_offset = int(match.group(1))
    if xref_offset < 0 or not payload[xref_offset:].startswith(b"xref"):
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has an invalid PDF startxref offset."
        )
    trailer_offset = payload.find(b"trailer", xref_offset + len(b"xref"))
    if trailer_offset < 0:
        raise PhotonKickArtifactError(f"Transient companion at {path} has no PDF trailer.")
    lines = payload[xref_offset + len(b"xref") : trailer_offset].splitlines()
    entries: dict[int, tuple[int, int]] = {}
    cursor = 0
    while cursor < len(lines):
        line = lines[cursor].strip()
        cursor += 1
        if not line:
            continue
        header = line.split()
        if len(header) != 2 or not all(token.isdigit() for token in header):
            raise PhotonKickArtifactError(
                f"Transient companion at {path} has a malformed PDF xref subsection."
            )
        first, count = (int(token) for token in header)
        if count <= 0 or cursor + count > len(lines):
            raise PhotonKickArtifactError(
                f"Transient companion at {path} has a truncated PDF xref subsection."
            )
        for index in range(count):
            fields = lines[cursor + index].strip().split()
            if (
                len(fields) != 3
                or len(fields[0]) != 10
                or len(fields[1]) != 5
                or not fields[0].isdigit()
                or not fields[1].isdigit()
                or fields[2] not in {b"n", b"f"}
            ):
                raise PhotonKickArtifactError(
                    f"Transient companion at {path} has a malformed PDF xref entry."
                )
            if fields[2] == b"n":
                entries[first + index] = (int(fields[0]), int(fields[1]))
        cursor += count
    if not entries:
        raise PhotonKickArtifactError(f"Transient companion at {path} has no live PDF objects.")
    return entries


def _pdf_object(
    payload: bytes,
    entries: Mapping[int, tuple[int, int]],
    object_number: int,
    generation: int,
    *,
    path: Path,
) -> bytes:
    entry = entries.get(object_number)
    if entry is None or entry[1] != generation:
        raise PhotonKickArtifactError(
            f"Transient companion at {path} references a missing PDF object."
        )
    offset = entry[0]
    header = re.compile(
        rb"\A" + str(object_number).encode() + rb"\s+" + str(generation).encode() + rb"\s+obj\b"
    )
    match = header.match(payload[offset:])
    if match is None:
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has a false PDF object offset."
        )
    body_start = offset + match.end()
    later_offsets = [
        candidate_offset
        for candidate_offset, _candidate_generation in entries.values()
        if candidate_offset > offset
    ]
    object_limit = min(later_offsets, default=len(payload))
    body_end = payload.rfind(b"endobj", body_start, object_limit)
    if body_end < 0:
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has an unterminated PDF object."
        )
    return payload[body_start:body_end]


def _pdf_stream_payload(
    payload: bytes,
    entries: Mapping[int, tuple[int, int]],
    object_number: int,
    generation: int,
    *,
    path: Path,
) -> bytes:
    body = _pdf_object(
        payload,
        entries,
        object_number,
        generation,
        path=path,
    )
    stream_marker = re.search(rb"\bstream\r?\n", body)
    if stream_marker is None:
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has a page content object without a stream."
        )
    dictionary = body[: stream_marker.start()]
    direct_length = re.search(rb"/Length\s+(\d+)(?!\s+\d+\s+R)", dictionary)
    indirect_length = re.search(rb"/Length\s+(\d+)\s+(\d+)\s+R", dictionary)
    if indirect_length is not None:
        length_object = _pdf_object(
            payload,
            entries,
            int(indirect_length.group(1)),
            int(indirect_length.group(2)),
            path=path,
        )
        if re.fullmatch(rb"\s*(\d+)\s*", length_object) is None:
            raise PhotonKickArtifactError(
                f"Transient companion at {path} has an invalid PDF stream length object."
            )
        length = int(length_object.strip())
    elif direct_length is not None:
        length = int(direct_length.group(1))
    else:
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has a page stream without a length."
        )
    stream_start = stream_marker.end()
    stream_end = stream_start + length
    if length <= 0 or stream_end > len(body):
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has an empty or truncated PDF page stream."
        )
    encoded = body[stream_start:stream_end]
    if body[stream_end:].lstrip(b"\r\n \t")[:9] != b"endstream":
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has a malformed PDF page stream."
        )
    filters = re.findall(rb"/Filter\s*/([A-Za-z0-9]+)", dictionary)
    if filters == [b"FlateDecode"]:
        try:
            decoded = zlib.decompress(encoded)
        except zlib.error as exc:
            raise PhotonKickArtifactError(
                f"Transient companion at {path} has an invalid compressed PDF page stream."
            ) from exc
    elif not filters:
        decoded = encoded
    else:
        raise PhotonKickArtifactError(
            f"Transient companion at {path} uses an unsupported PDF page-stream filter."
        )
    if not decoded.strip():
        raise PhotonKickArtifactError(f"Transient companion at {path} has an empty PDF page.")
    return decoded


def _validate_single_nonempty_pdf_page(payload: bytes, *, path: Path) -> None:
    if not re.match(rb"\A%PDF-\d\.\d(?:\r?\n)", payload):
        raise PhotonKickArtifactError(f"Transient companion at {path} has no valid PDF header.")
    entries = _classic_pdf_xref(payload, path=path)
    startxref_match = _PDF_STARTXREF_RE.search(payload)
    if startxref_match is None:  # already rejected by _classic_pdf_xref
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has no terminal PDF xref/EOF record."
        )
    trailer_offset = payload.find(
        b"trailer",
        int(startxref_match.group(1)),
    )
    trailer = payload[trailer_offset : payload.find(b"startxref", trailer_offset)]
    if re.search(rb"/Prev\s+\d+", trailer) is not None:
        raise PhotonKickArtifactError(
            f"Transient companion at {path} uses an incremental PDF update."
        )
    root_match = re.search(rb"/Root\s+(\d+)\s+(\d+)\s+R", trailer)
    if root_match is None:
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has no PDF catalog reference."
        )
    catalog = _pdf_object(
        payload,
        entries,
        int(root_match.group(1)),
        int(root_match.group(2)),
        path=path,
    )
    if re.search(rb"/Type\s*/Catalog\b", catalog) is None:
        raise PhotonKickArtifactError(f"Transient companion at {path} has an invalid PDF catalog.")
    pages_match = re.search(rb"/Pages\s+(\d+)\s+(\d+)\s+R", catalog)
    if pages_match is None:
        raise PhotonKickArtifactError(f"Transient companion at {path} has no PDF page tree.")
    pages = _pdf_object(
        payload,
        entries,
        int(pages_match.group(1)),
        int(pages_match.group(2)),
        path=path,
    )
    count_match = re.search(rb"/Count\s+(\d+)", pages)
    kids_match = re.search(rb"/Kids\s*\[(.*?)\]", pages, flags=re.DOTALL)
    kids = _PDF_REF_RE.findall(kids_match.group(1)) if kids_match is not None else []
    if count_match is None or int(count_match.group(1)) != 1 or len(kids) != 1:
        raise PhotonKickArtifactError(
            f"Transient companion at {path} must contain exactly one PDF page."
        )
    page = _pdf_object(
        payload,
        entries,
        int(kids[0][0]),
        int(kids[0][1]),
        path=path,
    )
    if re.search(rb"/Type\s*/Page(?!s)\b", page) is None:
        raise PhotonKickArtifactError(
            f"Transient companion at {path} page tree does not reference a page."
        )
    contents_array = re.search(rb"/Contents\s*\[(.*?)\]", page, flags=re.DOTALL)
    if contents_array is not None:
        content_refs = _PDF_REF_RE.findall(contents_array.group(1))
    else:
        contents = re.search(rb"/Contents\s+(\d+)\s+(\d+)\s+R", page)
        content_refs = [(contents.group(1), contents.group(2))] if contents is not None else []
    if not content_refs:
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has a PDF page without content."
        )
    decoded_streams = [
        _pdf_stream_payload(
            payload,
            entries,
            int(number),
            int(generation),
            path=path,
        )
        for number, generation in content_refs
    ]
    if not any(stream.strip() for stream in decoded_streams):
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has no nonempty PDF page content."
        )
    if not any(_PDF_SEMANTIC_MARK_RE.search(stream) for stream in decoded_streams):
        raise PhotonKickArtifactError(
            f"Transient companion at {path} has no plotted or text content "
            "beyond the Matplotlib page background."
        )


def companion_artifact_record(path: Path) -> CompanionArtifactRecord:
    """Parse and hash exactly one complete, nonempty companion PDF page."""
    try:
        payload = path.read_bytes()
    except OSError as exc:
        raise PhotonKickArtifactError(
            f"Cannot read transient companion PDF at {path}: {exc}"
        ) from exc
    _validate_single_nonempty_pdf_page(payload, path=path)
    return CompanionArtifactRecord(
        sha256=hashlib.sha256(payload).hexdigest(),
        size_bytes=len(payload),
    )


@contextmanager
def _artifact_lock(path: Path, *, exclusive: bool) -> Iterator[None]:
    """Hold an OS lock while reading or publishing one canonical pair."""
    lock_path = path.with_suffix(path.suffix + ".lock")
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with lock_path.open("a+b") as stream:
        stream.seek(0, os.SEEK_END)
        if stream.tell() == 0:
            stream.write(b"\0")
            stream.flush()
        stream.seek(0)
        try:
            if os.name == "nt":
                import msvcrt

                # Windows has no shared byte-range lock through msvcrt.  An
                # exclusive reader lock is conservative and prevents a mixed
                # CSV/PDF snapshot just as effectively.
                msvcrt.locking(stream.fileno(), msvcrt.LK_NBLCK, 1)
            else:
                import fcntl

                operation = (
                    fcntl.LOCK_EX  # type: ignore[attr-defined]
                    if exclusive
                    else fcntl.LOCK_SH  # type: ignore[attr-defined]
                )
                fcntl.flock(  # type: ignore[attr-defined]
                    stream.fileno(),
                    operation | fcntl.LOCK_NB,  # type: ignore[attr-defined]
                )
        except OSError as exc:
            role = "publisher" if exclusive else "reader"
            raise PhotonKickArtifactError(
                f"Another transient artifact reader/publisher holds {lock_path}; "
                f"refusing concurrent {role} access."
            ) from exc
        try:
            yield
        finally:
            stream.seek(0)
            if os.name == "nt":
                msvcrt.locking(stream.fileno(), msvcrt.LK_UNLCK, 1)
            else:
                fcntl.flock(  # type: ignore[attr-defined]
                    stream.fileno(),
                    fcntl.LOCK_UN,  # type: ignore[attr-defined]
                )


_THREAD_ENVIRONMENT_KEYS = (
    "BLIS_NUM_THREADS",
    "MKL_CBWR",
    "MKL_DYNAMIC",
    "MKL_NUM_THREADS",
    "OMP_DYNAMIC",
    "OMP_NUM_THREADS",
    "OPENBLAS_CORETYPE",
    "OPENBLAS_NUM_THREADS",
)


def _numeric_build_provenance(module: Any) -> dict[str, Any]:
    """Return portable BLAS/LAPACK/compiler facts from NumPy-style config."""
    config = getattr(getattr(module, "__config__", None), "CONFIG", {})
    if not isinstance(config, Mapping):
        return {}
    dependencies = config.get("Build Dependencies", {})
    dependency_result: dict[str, Any] = {}
    if isinstance(dependencies, Mapping):
        for name in ("blas", "lapack"):
            raw = dependencies.get(name, {})
            if not isinstance(raw, Mapping):
                continue
            dependency_result[name] = {
                key: raw[key]
                for key in (
                    "detection method",
                    "found",
                    "name",
                    "openblas configuration",
                    "version",
                )
                if key in raw
            }
    compilers = config.get("Compilers", {})
    compiler_result: dict[str, Any] = {}
    if isinstance(compilers, Mapping):
        for name, raw in compilers.items():
            if isinstance(raw, Mapping):
                compiler_result[str(name)] = {
                    key: raw[key] for key in ("name", "version") if key in raw
                }
    return {
        "build_dependencies": dependency_result,
        "compilers": compiler_result,
    }


def producer_runtime_provenance() -> dict[str, Any]:
    """Capture the numerical runtime without installation-specific paths."""
    import matplotlib
    import scipy

    multiarray = getattr(getattr(np, "_core", None), "_multiarray_umath", None)
    raw_cpu_features = getattr(multiarray, "__cpu_features__", {})
    cpu_features = (
        {str(name): bool(enabled) for name, enabled in sorted(raw_cpu_features.items())}
        if isinstance(raw_cpu_features, Mapping)
        else {}
    )
    return {
        "matplotlib": {
            "backend": str(matplotlib.get_backend()),
            "freetype": getattr(
                getattr(matplotlib, "ft2font", None),
                "__freetype_version__",
                None,
            ),
            "version": matplotlib.__version__,
        },
        "numpy": {
            "build": _numeric_build_provenance(np),
            "version": np.__version__,
        },
        "platform": {
            "machine": platform.machine(),
            "processor": platform.processor(),
            "release": platform.release(),
            "system": platform.system(),
        },
        "python": {
            "byteorder": sys.byteorder,
            "compiler": platform.python_compiler(),
            "implementation": platform.python_implementation(),
            "version": platform.python_version(),
        },
        "runtime_cpu_features": cpu_features,
        "scipy": {
            "build": _numeric_build_provenance(scipy),
            "version": scipy.__version__,
        },
        "thread_environment": {name: os.environ.get(name) for name in _THREAD_ENVIRONMENT_KEYS},
    }


@dataclass(frozen=True)
class PhotonKickResult:
    E: np.ndarray
    snapshot_times: np.ndarray
    f_snapshots: np.ndarray  # shape (n_snapshots, NE)
    x_qp_snapshots: np.ndarray  # shape (n_snapshots,)
    f_steady_state: np.ndarray  # shape (NE,)
    x_qp_steady_state: float


def _material() -> Material:
    return Material(
        name="Al_Fischer2024",
        Delta_0=DELTA_0,
        T_c=T_C,
        tau_0=TAU_0,
    )


def _build_state(material: Material) -> T3DiffusionState:
    E, _ = build_energy_grid(
        gap=DELTA_0,
        energy_min_factor=E_MIN_FACTOR,
        energy_max_factor=E_MAX_FACTOR,
        num_energy_bins=NUM_BINS,
    )
    dE = integration_widths_from_centers(E)
    spectral = SpectralContext(E_bins=E, dE_bins=dE, gap=DELTA_0)
    omega, _, _, _ = build_phonon_frequency_map(E)
    phonon = PhononState(
        n_ph=thermal_phonon_occupation(omega, T_BATH).reshape(1, -1, 1),
        omega_bins=omega.reshape(1, -1),
        tau_l=np.zeros((1, omega.size)),
        model=PhononModel.PH0_LOCAL,
        branches=[PhononBranchSpec(name="debye_average")],
    )
    f_FD = fermi_dirac_occupation(E, T_BATH)
    return T3DiffusionState(
        f=f_FD,
        gap=DELTA_0,
        spectral=spectral,
        phonon=phonon,
        material=material,
        T_bath=T_BATH,
    )


def run() -> PhotonKickResult:
    material = _material()
    backend = T3DiffusionBackend()
    state = _build_state(material)

    pb_photon_params = {
        "omega_PB": OMEGA_PB,
        "n_bar_PB": N_BAR_PB,
        "c_phot_PB": C_PHOT_PB,
    }

    transient = run_time_dependent(
        state,
        dt=DT,
        total_time=TOTAL_TIME,
        snapshot_interval=SNAPSHOT_INTERVAL,
        pb_photon_params=pb_photon_params,
        observables={
            "x_qp": lambda s: qp_fraction(s.f, s.spectral, delta_0=DELTA_0),
        },
        backend=backend,
    )

    # Reference steady state (τ_l = 0 Newton solve) for overlay.
    driven_ss = backend.steady_state(
        state,
        use_thermal_phonons=True,
        pb_photon_params=pb_photon_params,
        newton_tol=1e-14,
        newton_max_iter=500,
    )
    x_qp_ss = float(qp_fraction(driven_ss.f, driven_ss.spectral, delta_0=DELTA_0))

    times = np.array([snap.t for snap in transient.snapshots], dtype=float)
    f_arr = np.stack([snap.f for snap in transient.snapshots], axis=0)
    x_qp_arr = np.array(
        [snap.observables["x_qp"] for snap in transient.snapshots],
        dtype=float,
    )

    return PhotonKickResult(
        E=state.spectral.E,
        snapshot_times=times,
        f_snapshots=f_arr,
        x_qp_snapshots=x_qp_arr,
        f_steady_state=driven_ss.f,
        x_qp_steady_state=x_qp_ss,
    )


@dataclass(frozen=True)
class PhotonKickBaseline:
    E: np.ndarray
    snapshot_times: np.ndarray
    f_snapshots: np.ndarray  # shape (n_snapshots, NE)
    x_qp_snapshots: np.ndarray  # shape (n_snapshots,)
    f_steady_state: np.ndarray  # shape (NE,)
    x_qp_steady_state: float
    fingerprint: dict[str, Any]
    trajectory_evidence_scope: str


def baseline_path() -> Path:
    root = Path(__file__).resolve().parents[2]
    return root / "validation" / "baselines" / "transient" / "photon_kick_response.csv"


def plot_path() -> Path:
    return baseline_path().with_suffix(".pdf")


_METADATA_KEYS = {
    "columns",
    "companion_pdf",
    "fingerprint",
    "payload_sha256",
    "producer_runtime",
    "provenance_note",
    "row_count",
    "schema",
    "snapshot_times_ns",
    "steady_state_certificate",
    "trajectory_evidence_scope",
    "x_qp_snapshots",
    "x_qp_steady_state",
}


def _x_qp_from_occupations(
    E: np.ndarray,
    f_snapshots: np.ndarray,
    f_steady_state: np.ndarray,
) -> tuple[np.ndarray, float]:
    spectral = SpectralContext(
        E_bins=E,
        dE_bins=integration_widths_from_centers(E),
        gap=DELTA_0,
    )
    snapshots = np.asarray(
        [qp_fraction(values, spectral, delta_0=DELTA_0) for values in f_snapshots],
        dtype=float,
    )
    steady = float(qp_fraction(f_steady_state, spectral, delta_0=DELTA_0))
    return snapshots, steady


def _normwise_backward_error(
    residual: np.ndarray,
    gain: np.ndarray,
    loss_term: np.ndarray,
) -> float:
    """Stable L1 backward error for one persisted QP balance."""
    common = float(
        max(
            np.max(np.abs(residual), initial=0.0),
            np.max(np.abs(gain), initial=0.0),
            np.max(np.abs(loss_term), initial=0.0),
        )
    )
    if common == 0.0:
        return 0.0
    numerator = float(np.sum(np.abs(residual) / common))
    denominator = float(np.sum(np.abs(gain) / common) + np.sum(np.abs(loss_term) / common))
    return numerator / denominator if denominator > 0.0 else float("inf")


def _weighted_pair_number_error(
    pair_gain: np.ndarray,
    pair_loss_rate: np.ndarray,
    f: np.ndarray,
    weights: np.ndarray,
    active: np.ndarray,
) -> float:
    """Certify the number-changing mode without scattering turnover."""
    gain = pair_gain[active]
    loss_term = pair_loss_rate[active] * f[active]
    weight = weights[active]
    common = float(
        max(
            np.max(np.abs(gain), initial=0.0),
            np.max(np.abs(loss_term), initial=0.0),
        )
    )
    if common == 0.0:
        return float("inf")
    gain_scaled = weight * (gain / common)
    loss_scaled = weight * (loss_term / common)
    denominator = float(np.sum(np.abs(gain_scaled)) + np.sum(np.abs(loss_scaled)))
    if denominator == 0.0:
        return float("inf")
    return abs(float(np.sum(gain_scaled - loss_scaled))) / denominator


def _steady_state_certificate(E: np.ndarray, f: np.ndarray) -> dict[str, float | str]:
    """Reassemble the thermal-phonon + PB-photon steady-state equation."""
    spectral = SpectralContext(
        E_bins=E,
        dE_bins=integration_widths_from_centers(E),
        gap=DELTA_0,
    )
    material = _material()
    K_s0 = build_scattering_kernel_base(
        spectral,
        tau_0=material.tau_0,
        T_c=material.T_c,
    )
    K_r0 = build_recombination_kernel_base(
        spectral,
        tau_0=material.tau_0,
        T_c=material.T_c,
    )
    gain_phonon, loss_phonon = phonon_collision_rates(
        f,
        spectral,
        K_s0,
        K_r0,
        T_BATH,
    )
    gain_pair_phonon, loss_pair_phonon = phonon_collision_rates(
        f,
        spectral,
        None,
        K_r0,
        T_BATH,
    )
    (
        gain_scattering_photon,
        loss_scattering_photon,
        gain_pair_photon,
        loss_pair_photon,
    ) = pair_breaking_photon_collision_components(
        f,
        spectral,
        OMEGA_PB,
        N_BAR_PB,
        C_PHOT_PB,
    )
    gain = gain_phonon + gain_scattering_photon + gain_pair_photon
    loss_rate = loss_phonon + loss_scattering_photon + loss_pair_photon
    active = spectral.active_mask
    gain_active = gain[active]
    loss_term = loss_rate[active] * f[active]
    residual = gain_active - loss_term
    certificate: dict[str, float | str] = {
        "metric": STEADY_STATE_CERTIFICATE_METRIC,
        "qp_backward_error": _normwise_backward_error(
            residual,
            gain_active,
            loss_term,
        ),
        "qp_residual_inf": float(np.max(np.abs(residual), initial=0.0)),
        "qp_number_backward_error": _weighted_pair_number_error(
            gain_pair_phonon + gain_pair_photon,
            loss_pair_phonon + loss_pair_photon,
            f,
            spectral.cell_weights,
            active,
        ),
    }
    return _validated_steady_state_certificate(
        certificate,
        context="reassembled transient steady state",
    )


def _validated_steady_state_certificate(
    raw: Mapping[str, Any],
    *,
    context: str,
) -> dict[str, float | str]:
    expected = {"metric", *STEADY_STATE_CERTIFICATE_FIELDS}
    if set(raw) != expected or raw.get("metric") != STEADY_STATE_CERTIFICATE_METRIC:
        raise PhotonKickArtifactError(f"{context} has an incomplete or stale certificate record.")
    result: dict[str, float | str] = {"metric": STEADY_STATE_CERTIFICATE_METRIC}
    limits = {
        "qp_backward_error": STEADY_STATE_BACKWARD_ERROR_LIMIT,
        "qp_residual_inf": STEADY_STATE_RESIDUAL_INF_LIMIT,
        "qp_number_backward_error": STEADY_STATE_NUMBER_ERROR_LIMIT,
    }
    for field in STEADY_STATE_CERTIFICATE_FIELDS:
        value = raw[field]
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise PhotonKickArtifactError(f"{context} field {field!r} is not numeric.")
        number = float(value)
        if not np.isfinite(number) or number < 0.0 or number >= limits[field]:
            raise PhotonKickArtifactError(
                f"{context} field {field!r}={number:.3e} does not satisfy "
                f"the {limits[field]:.3e} gate."
            )
        result[field] = number
    return result


def _bind_steady_state_certificate(
    stamped: Mapping[str, Any],
    reassembled: Mapping[str, Any],
    *,
    context: str,
) -> dict[str, float | str]:
    stamped_valid = _validated_steady_state_certificate(
        stamped,
        context=f"{context} stamped",
    )
    reassembled_valid = _validated_steady_state_certificate(
        reassembled,
        context=f"{context} reassembled",
    )
    for field in STEADY_STATE_CERTIFICATE_FIELDS:
        if not np.isclose(
            float(stamped_valid[field]),
            float(reassembled_valid[field]),
            rtol=STEADY_STATE_CERTIFICATE_BINDING_RTOL,
            atol=0.0,
        ):
            raise PhotonKickArtifactError(
                f"{context} field {field!r} does not match fresh reassembly."
            )
    return reassembled_valid


def _validate_transient_semantics(
    E: np.ndarray,
    times: np.ndarray,
    f_snapshots: np.ndarray,
    x_qp: np.ndarray,
    f_steady: np.ndarray,
    x_qp_steady: float,
    *,
    context: str,
) -> None:
    """Validate stored snapshot semantics without claiming path integration.

    The sparse snapshots cannot independently prove the intervening ETD2
    steps.  The slow live-recompute regression owns that dynamics claim; this
    routine checks only the state domain, initial condition, response
    monotonicity, and endpoint agreement advertised by
    :data:`TRAJECTORY_EVIDENCE_SCOPE`.
    """
    thermal = fermi_dirac_occupation(E, T_BATH)
    if times[0] != 0.0 or np.any(times < 0.0):
        raise PhotonKickArtifactError(
            f"{context} must begin exactly at t=0 and contain no negative time."
        )
    if not np.allclose(
        f_snapshots[0],
        thermal,
        rtol=8.0 * np.finfo(np.float64).eps,
        atol=0.0,
    ):
        raise PhotonKickArtifactError(
            f"{context} t=0 occupation is not the thermal Fermi-Dirac seed "
            "within the cross-libm rounding envelope."
        )
    if np.any(np.diff(x_qp) < 0.0):
        raise PhotonKickArtifactError(
            f"{context} has a decreasing x_qp segment under the constant PB drive."
        )
    if not x_qp_steady > x_qp[0]:
        raise PhotonKickArtifactError(
            f"{context} driven steady state does not exceed its thermal seed."
        )
    relative_x_qp_gap = abs(float(x_qp[-1] - x_qp_steady)) / x_qp_steady
    if relative_x_qp_gap > FINAL_X_QP_RELATIVE_GAP_LIMIT:
        raise PhotonKickArtifactError(
            f"{context} final x_qp is {relative_x_qp_gap:.3%} from the stored "
            f"steady state; limit {FINAL_X_QP_RELATIVE_GAP_LIMIT:.1%}."
        )
    spectral = SpectralContext(
        E_bins=E,
        dE_bins=integration_widths_from_centers(E),
        gap=DELTA_0,
    )
    weighted_denominator = float(np.sum(spectral.cell_weights * np.abs(f_steady)))
    weighted_gap = (
        float(np.sum(spectral.cell_weights * np.abs(f_snapshots[-1] - f_steady)))
        / weighted_denominator
        if weighted_denominator > 0.0
        else float("inf")
    )
    if weighted_gap > FINAL_OCCUPATION_WEIGHTED_L1_LIMIT:
        raise PhotonKickArtifactError(
            f"{context} final occupation is {weighted_gap:.3%} from the "
            "stored steady state in the BCS-capacity weighted L1 metric; "
            f"limit {FINAL_OCCUPATION_WEIGHTED_L1_LIMIT:.1%}."
        )


def _result_table(
    result: PhotonKickResult,
) -> tuple[np.ndarray, list[str], np.ndarray]:
    arrays = (
        np.asarray(result.E),
        np.asarray(result.snapshot_times),
        np.asarray(result.f_snapshots),
        np.asarray(result.f_steady_state),
        np.asarray(result.x_qp_snapshots),
    )
    if any(np.iscomplexobj(array) for array in arrays):
        raise ValueError("Transient artifact arrays must be real-valued.")
    E, times, f_snapshots, f_steady, x_qp = (np.asarray(array, dtype=float) for array in arrays)
    if E.ndim != 1 or times.ndim != 1:
        raise ValueError("Transient energy and snapshot-time arrays must be one-dimensional.")
    if f_snapshots.shape != (times.size, E.size):
        raise ValueError(
            "Transient f_snapshots shape must equal "
            f"(n_snapshots, n_energy)={(times.size, E.size)}."
        )
    if f_steady.shape != E.shape or x_qp.shape != times.shape:
        raise ValueError(
            "Transient steady-state and x_qp arrays must match their energy/time axes."
        )
    x_qp_ss = float(result.x_qp_steady_state)
    if (
        E.size == 0
        or times.size == 0
        or any(np.any(~np.isfinite(array)) for array in (E, times, f_snapshots, f_steady, x_qp))
        or not np.isfinite(x_qp_ss)
    ):
        raise ValueError("Transient artifact values must be non-empty and finite.")
    if np.any(np.diff(E) <= 0.0) or np.any(np.diff(times) <= 0.0):
        raise ValueError("Transient energy and snapshot-time axes must be strictly increasing.")
    if (
        np.any((f_snapshots < 0.0) | (f_snapshots > 1.0))
        or np.any((f_steady < 0.0) | (f_steady > 1.0))
        or np.any(x_qp < 0.0)
        or x_qp_ss < 0.0
    ):
        raise ValueError("Transient occupations and quasiparticle fractions are out of range.")
    x_qp_reassembled, x_qp_ss_reassembled = _x_qp_from_occupations(
        E,
        f_snapshots,
        f_steady,
    )
    consistency_rtol = 64.0 * np.finfo(np.float64).eps
    if not np.allclose(
        x_qp,
        x_qp_reassembled,
        rtol=consistency_rtol,
        atol=0.0,
    ) or not np.isclose(
        x_qp_ss,
        x_qp_ss_reassembled,
        rtol=consistency_rtol,
        atol=0.0,
    ):
        raise ValueError(
            "Transient x_qp values do not match independent qp_fraction "
            "reassembly from the persisted occupations."
        )
    _validate_transient_semantics(
        E,
        times,
        f_snapshots,
        x_qp,
        f_steady,
        x_qp_ss,
        context="Transient result",
    )
    table = np.column_stack((E, f_steady, f_snapshots.T))
    columns = ["E_uev", "f_steady_state", *[f"f_t={t:g}ns" for t in times]]
    return np.ascontiguousarray(table), columns, x_qp


def _payload_sha256(
    data: np.ndarray,
    snapshot_times: np.ndarray,
    x_qp_snapshots: np.ndarray,
    x_qp_steady_state: float,
) -> str:
    """Hash the exact persisted numerical payload and scalar/axis metadata."""
    digest = hashlib.sha256()
    digest.update(f"shape={data.shape}\n".encode())
    digest.update(b"snapshot_times_ns=")
    digest.update(",".join(f"{float(value):.17e}" for value in snapshot_times).encode())
    digest.update(b"\n")
    digest.update(b"x_qp_snapshots=")
    digest.update(",".join(f"{float(value):.17e}" for value in x_qp_snapshots).encode())
    digest.update(b"\n")
    digest.update(f"x_qp_steady_state={x_qp_steady_state:.17e}\n".encode())
    for row in data:
        digest.update(",".join(f"{float(value):.17e}" for value in row).encode())
        digest.update(b"\n")
    return digest.hexdigest()


def read_baseline(
    path: Path | None = None,
    *,
    companion_pdf_path: Path | None = None,
    require_current: bool = True,
) -> PhotonKickBaseline:
    """Read one CSV/PDF snapshot while excluding concurrent publication."""
    resolved_path = baseline_path() if path is None else path
    with _artifact_lock(resolved_path, exclusive=False):
        return _read_baseline_unlocked(
            resolved_path,
            companion_pdf_path=companion_pdf_path,
            require_current=require_current,
        )


def _read_baseline_unlocked(
    path: Path,
    *,
    companion_pdf_path: Path | None,
    require_current: bool,
) -> PhotonKickBaseline:
    """Read a complete artifact, rejecting stale source/configuration pins."""
    if companion_pdf_path is None:
        companion_pdf_path = path.with_suffix(".pdf")
    try:
        with path.open(encoding="utf-8", newline="") as fp:
            csv_rows = list(csv.reader(fp))
    except (OSError, UnicodeError) as exc:
        raise PhotonKickArtifactError(f"Cannot read transient artifact at {path}: {exc}") from exc

    schema_row = [f"# qpsim_artifact_schema={ARTIFACT_SCHEMA}"]
    if not csv_rows or csv_rows[0] != schema_row:
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} is legacy or has the wrong schema; "
            f"expected {schema_row[0]!r}."
        )
    if len(csv_rows) < 4 or len(csv_rows[1]) != 1:
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} is missing its unique metadata record."
        )
    marker = "# qpsim_metadata="
    if not csv_rows[1][0].startswith(marker):
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} is missing its unique metadata record."
        )
    try:
        metadata = json.loads(csv_rows[1][0][len(marker) :])
    except (json.JSONDecodeError, TypeError) as exc:
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} has malformed JSON metadata."
        ) from exc
    if not isinstance(metadata, dict) or set(metadata) != _METADATA_KEYS:
        actual = set(metadata) if isinstance(metadata, dict) else set()
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} metadata fields differ from the schema; "
            f"missing={sorted(_METADATA_KEYS - actual)}, "
            f"extra={sorted(actual - _METADATA_KEYS)}."
        )
    if metadata["schema"] != ARTIFACT_SCHEMA:
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} has stale schema {metadata['schema']!r}."
        )
    fingerprint = metadata["fingerprint"]
    if not isinstance(fingerprint, dict):
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} has malformed source/configuration provenance."
        )
    if require_current and fingerprint != solver_fingerprint():
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} was not produced by the current executable source "
            "and solver configuration; regenerate it."
        )
    producer_runtime = metadata["producer_runtime"]
    if (
        not isinstance(producer_runtime, dict)
        or set(producer_runtime)
        != {
            "matplotlib",
            "numpy",
            "platform",
            "python",
            "runtime_cpu_features",
            "scipy",
            "thread_environment",
        }
        or not isinstance(producer_runtime["runtime_cpu_features"], dict)
        or not isinstance(producer_runtime["thread_environment"], dict)
        or set(producer_runtime["thread_environment"]) != set(_THREAD_ENVIRONMENT_KEYS)
    ):
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} has malformed producer runtime provenance."
        )
    for library in ("matplotlib", "numpy", "scipy"):
        record = producer_runtime[library]
        if not isinstance(record, dict) or not isinstance(record.get("version"), str):
            raise PhotonKickArtifactError(
                f"Transient artifact at {path} has malformed {library} provenance."
            )

    columns = metadata["columns"]
    if (
        not isinstance(columns, list)
        or not all(isinstance(value, str) for value in columns)
        or csv_rows[2] != columns
        or len(set(columns)) != len(columns)
    ):
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} has malformed or inconsistent columns."
        )
    if (
        not isinstance(metadata["snapshot_times_ns"], list)
        or not isinstance(metadata["row_count"], int)
        or isinstance(metadata["row_count"], bool)
        or not isinstance(metadata["x_qp_snapshots"], list)
        or not isinstance(metadata["x_qp_steady_state"], (int, float))
        or isinstance(metadata["x_qp_steady_state"], bool)
    ):
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} has malformed payload metadata types."
        )
    try:
        times = np.asarray(metadata["snapshot_times_ns"], dtype=float)
        x_qp = np.asarray(metadata["x_qp_snapshots"], dtype=float)
        x_qp_ss = float(metadata["x_qp_steady_state"])
        row_count = metadata["row_count"]
        data = np.asarray(
            [[float(value) for value in row] for row in csv_rows[3:]],
            dtype=float,
        )
    except (TypeError, ValueError) as exc:
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} has non-numeric payload metadata or rows."
        ) from exc
    expected_columns = (
        [
            "E_uev",
            "f_steady_state",
            *[f"f_t={value:g}ns" for value in times],
        ]
        if times.ndim == 1
        else []
    )
    if (
        times.ndim != 1
        or times.size == 0
        or np.any(~np.isfinite(times))
        or np.any(np.diff(times) <= 0.0)
        or x_qp.shape != times.shape
        or np.any(~np.isfinite(x_qp))
        or np.any(x_qp < 0.0)
        or not np.isfinite(x_qp_ss)
        or x_qp_ss < 0.0
        or columns != expected_columns
        or row_count != len(csv_rows) - 3
        or data.shape != (row_count, len(columns))
        or np.any(~np.isfinite(data))
        or np.any(np.diff(data[:, 0]) <= 0.0)
        or np.any((data[:, 1:] < 0.0) | (data[:, 1:] > 1.0))
    ):
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} has an inconsistent or invalid numerical table."
        )
    if metadata["provenance_note"] != BASELINE_PROVENANCE:
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} has stale descriptive provenance."
        )
    if metadata["trajectory_evidence_scope"] != TRAJECTORY_EVIDENCE_SCOPE:
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} misstates its trajectory evidence scope."
        )
    if require_current:
        expected_times = np.arange(
            0.0,
            TOTAL_TIME + 0.5 * SNAPSHOT_INTERVAL,
            SNAPSHOT_INTERVAL,
        )
        expected_E, _ = build_energy_grid(
            gap=DELTA_0,
            energy_min_factor=E_MIN_FACTOR,
            energy_max_factor=E_MAX_FACTOR,
            num_energy_bins=NUM_BINS,
        )
        if (
            row_count != NUM_BINS
            or not np.array_equal(data[:, 0], expected_E)
            or not np.allclose(
                times,
                expected_times,
                rtol=0.0,
                atol=1.0e-9,
            )
        ):
            raise PhotonKickArtifactError(
                f"Transient artifact at {path} has stale grid or snapshot dimensions."
            )
    if metadata["payload_sha256"] != _payload_sha256(
        data,
        times,
        x_qp,
        x_qp_ss,
    ):
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} payload hash does not match its table."
        )
    reassembled_x_qp, reassembled_x_qp_ss = _x_qp_from_occupations(
        data[:, 0],
        np.ascontiguousarray(data[:, 2:].T),
        data[:, 1],
    )
    consistency_rtol = 64.0 * np.finfo(np.float64).eps
    if not np.allclose(
        x_qp,
        reassembled_x_qp,
        rtol=consistency_rtol,
        atol=0.0,
    ) or not np.isclose(
        x_qp_ss,
        reassembled_x_qp_ss,
        rtol=consistency_rtol,
        atol=0.0,
    ):
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} has x_qp values inconsistent with "
            "its persisted occupations."
        )
    f_snapshots = np.ascontiguousarray(data[:, 2:].T)
    _validate_transient_semantics(
        data[:, 0],
        times,
        f_snapshots,
        x_qp,
        data[:, 1],
        x_qp_ss,
        context=f"Transient artifact at {path}",
    )
    certificate = metadata["steady_state_certificate"]
    if not isinstance(certificate, dict):
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} has a malformed steady-state certificate."
        )
    _bind_steady_state_certificate(
        certificate,
        _steady_state_certificate(data[:, 0], data[:, 1]),
        context=f"Transient artifact at {path} steady-state certificate",
    )

    companion = metadata["companion_pdf"]
    if (
        not isinstance(companion, dict)
        or set(companion) != {"sha256", "size_bytes"}
        or not isinstance(companion["sha256"], str)
        or len(companion["sha256"]) != 64
        or any(character not in "0123456789abcdef" for character in companion["sha256"])
        or not isinstance(companion["size_bytes"], int)
        or companion["size_bytes"] <= 0
    ):
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} has malformed companion-PDF provenance."
        )
    actual_companion = companion_artifact_record(companion_pdf_path)
    if companion != {
        "sha256": actual_companion.sha256,
        "size_bytes": actual_companion.size_bytes,
    }:
        raise PhotonKickArtifactError(
            f"Transient artifact at {path} does not authenticate companion PDF "
            f"{companion_pdf_path}."
        )
    return PhotonKickBaseline(
        E=data[:, 0],
        snapshot_times=times,
        f_snapshots=f_snapshots,
        x_qp_snapshots=x_qp,
        f_steady_state=data[:, 1],
        x_qp_steady_state=x_qp_ss,
        fingerprint=fingerprint,
        trajectory_evidence_scope=TRAJECTORY_EVIDENCE_SCOPE,
    )


def write_baseline(
    result: PhotonKickResult,
    path: Path,
    *,
    companion_pdf: CompanionArtifactRecord,
    fingerprint: dict[str, Any] | None = None,
    producer_runtime: dict[str, Any] | None = None,
) -> Path:
    """Atomically write a non-canonical CSV bound to one already-staged PDF."""
    if path.resolve() == baseline_path().resolve():
        raise PhotonKickArtifactError(
            "Direct canonical transient CSV writes are forbidden; use "
            "publish_baseline_pair() or generate_baseline()."
        )
    if fingerprint is None:
        fingerprint = solver_fingerprint()
    if producer_runtime is None:
        producer_runtime = producer_runtime_provenance()
    if (
        len(companion_pdf.sha256) != 64
        or any(character not in "0123456789abcdef" for character in companion_pdf.sha256)
        or companion_pdf.size_bytes <= 0
    ):
        raise ValueError("Companion PDF record must contain a SHA-256 and positive size.")
    data, columns, x_qp = _result_table(result)
    times = np.asarray(result.snapshot_times, dtype=float)
    x_qp_ss = float(result.x_qp_steady_state)
    steady_state_certificate = _steady_state_certificate(
        np.asarray(result.E, dtype=float),
        np.asarray(result.f_steady_state, dtype=float),
    )
    metadata = {
        "columns": columns,
        "companion_pdf": {
            "sha256": companion_pdf.sha256,
            "size_bytes": companion_pdf.size_bytes,
        },
        "fingerprint": fingerprint,
        "payload_sha256": _payload_sha256(data, times, x_qp, x_qp_ss),
        "producer_runtime": producer_runtime,
        "provenance_note": BASELINE_PROVENANCE,
        "row_count": data.shape[0],
        "schema": ARTIFACT_SCHEMA,
        "snapshot_times_ns": [float(value) for value in times],
        "steady_state_certificate": steady_state_certificate,
        "trajectory_evidence_scope": TRAJECTORY_EVIDENCE_SCOPE,
        "x_qp_snapshots": [float(value) for value in x_qp],
        "x_qp_steady_state": x_qp_ss,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as fp:
            temporary_path = Path(fp.name)
            writer = csv.writer(fp, lineterminator="\n")
            writer.writerow([f"# qpsim_artifact_schema={ARTIFACT_SCHEMA}"])
            writer.writerow([f"# qpsim_metadata={_canonical_json(metadata)}"])
            writer.writerow(columns)
            for row in data:
                writer.writerow([f"{float(value):.17e}" for value in row])
            fp.flush()
            os.fsync(fp.fileno())
        os.replace(temporary_path, path)
        temporary_path = None
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
    return path


def write_plot(result: PhotonKickResult, path: Path | None = None) -> Path:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    if path is None:
        path = plot_path()
    if path.resolve() == plot_path().resolve():
        raise PhotonKickArtifactError(
            "Direct canonical transient PDF writes are forbidden; use "
            "publish_baseline_pair() or generate_baseline()."
        )
    path.parent.mkdir(parents=True, exist_ok=True)

    fig, (ax_f, ax_x) = plt.subplots(
        2,
        1,
        figsize=(8, 8),
        gridspec_kw={"height_ratios": [3, 1]},
    )

    # Upper panel: f(E) snapshots (plasma colormap from t=0 dark →
    # t=TOTAL_TIME bright) + driven steady-state reference.
    x = result.E / DELTA_0
    n_snaps = result.snapshot_times.size
    cmap = matplotlib.colormaps["plasma"]
    colors = cmap(np.linspace(0.05, 0.85, n_snaps))

    f_FD = fermi_dirac_occupation(result.E, T_BATH)
    ax_f.semilogy(x, f_FD, "k:", lw=1.0, alpha=0.7, label=r"$f_\mathrm{FD}(T_B)$")

    plot_idxs = np.linspace(0, n_snaps - 1, min(n_snaps, 8)).astype(int)
    for idx in plot_idxs:
        ax_f.semilogy(
            x,
            result.f_snapshots[idx],
            "-",
            lw=1.2,
            color=colors[idx],
            alpha=0.85,
            label=rf"$t = {result.snapshot_times[idx]:.0f}$ ns",
        )
    ax_f.semilogy(
        x,
        result.f_steady_state,
        "k--",
        lw=1.8,
        label=r"driven steady state ($t \to \infty$)",
    )

    # Pair-breaking threshold: photons at ω_PB break pairs into QPs
    # at E and ω_PB - E, so QPs accumulate in a band [Δ, ω_PB - Δ].
    ax_f.axvline(
        (OMEGA_PB - DELTA_0) / DELTA_0,
        color="red",
        ls="--",
        lw=0.6,
        alpha=0.5,
        label=r"$\omega_\mathrm{PB}-\Delta$",
    )

    ax_f.set_xlabel(r"$E / \Delta_0$", fontsize=12)
    ax_f.set_ylabel(r"$f(E, t)$", fontsize=12)
    ax_f.set_xlim(1.0, 5.0)
    # Clip y-range to focus on where the transient actually evolves:
    # floor at the steady-state minimum, ceiling at the steady-state
    # peak × 10. The exponentially-suppressed f_FD tail at high E
    # extends orders of magnitude below this floor but carries no
    # story.
    ss_max = float(result.f_steady_state.max())
    ss_nonzero = result.f_steady_state[result.f_steady_state > 0]
    ss_min = float(ss_nonzero.min()) if ss_nonzero.size > 0 else 1e-12
    ax_f.set_ylim(max(ss_min / 10.0, 1e-14), ss_max * 10.0)
    ax_f.legend(fontsize=8, loc="lower left")
    ax_f.grid(True, which="both", ls=":", alpha=0.3)
    ax_f.set_title(
        "Photon-kick response: $f(E, t)$ climbs toward the driven steady state\n"
        rf"$T_B={T_BATH}$ K, $\omega_\mathrm{{PB}}=2.8\,\Delta_0$, "
        rf"$c\cdot\bar n={C_PHOT_PB * N_BAR_PB:.0e}$ ns$^{{-1}}$, "
        rf"$\tau_0={TAU_0:.0f}$ ns",
        fontsize=10,
    )

    # Lower panel: x_qp(t) — how fast we approach steady state.
    ax_x.plot(
        result.snapshot_times,
        result.x_qp_snapshots,
        "o-",
        lw=1.5,
        ms=4,
        color="tab:blue",
        label=r"$x_\mathrm{qp}^{(\mathrm{qpsim})}(t)$",
    )
    ax_x.axhline(
        result.x_qp_steady_state,
        color="k",
        ls="--",
        lw=1.0,
        label=(
            r"$x_\mathrm{qp}^{(\mathrm{qpsim}),\mathrm{ss}}="
            rf"{result.x_qp_steady_state:.3e}$"
        ),
    )
    ax_x.set_xlabel(r"$t$ [ns]", fontsize=12)
    ax_x.set_ylabel(
        r"$x_\mathrm{qp}^{(\mathrm{qpsim})}=N_\mathrm{qp}/(4\rho_F\Delta_0)$",
        fontsize=10,
    )
    ax_x.grid(True, which="both", ls=":", alpha=0.3)
    ax_x.legend(fontsize=8, loc="lower right")
    ax_x.text(
        0.01,
        0.97,
        r"Fischer convention: $x_\mathrm{qp}^{(\mathrm{paper})}"
        r"=2x_\mathrm{qp}^{(\mathrm{qpsim})}$",
        transform=ax_x.transAxes,
        ha="left",
        va="top",
        fontsize=7,
    )

    fig.text(
        0.5,
        0.004,
        PLOT_QUALIFICATION,
        ha="center",
        va="bottom",
        fontsize=6.5,
    )
    fig.tight_layout(rect=(0.0, 0.045, 1.0, 1.0))
    fig.savefig(
        path,
        format="pdf",
        metadata={
            "Title": "qpsim transient photon-kick response",
            "Subject": BASELINE_PROVENANCE,
        },
    )
    plt.close(fig)
    return path


def publish_baseline_pair(
    result: PhotonKickResult,
    *,
    fingerprint: dict[str, Any],
    producer_runtime: dict[str, Any],
) -> tuple[Path, Path]:
    """Serialize one canonical publisher against all concurrent readers."""
    with _artifact_lock(baseline_path(), exclusive=True):
        return _publish_baseline_pair_locked(
            result,
            fingerprint=fingerprint,
            producer_runtime=producer_runtime,
        )


def _publish_baseline_pair_locked(
    result: PhotonKickResult,
    *,
    fingerprint: dict[str, Any],
    producer_runtime: dict[str, Any],
) -> tuple[Path, Path]:
    """Stage, cross-authenticate, and promote the PDF/CSV pair safely.

    The PDF is promoted first and the CSV last.  The CSV is therefore the
    commit marker: an interruption may leave an unreferenced new PDF, but it
    cannot leave a current-looking CSV that authenticates an absent or partial
    companion.
    """
    csv_path = baseline_path()
    pdf_path = plot_path()
    if fingerprint != solver_fingerprint() or producer_runtime != producer_runtime_provenance():
        raise PhotonKickArtifactError(
            "Transient executable source/configuration or numerical runtime changed "
            "during the solve; "
            "discarding the result instead of publishing mixed provenance."
        )
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    csv_stage: Path | None = None
    pdf_stage: Path | None = None
    try:
        with NamedTemporaryFile(
            dir=pdf_path.parent,
            prefix=f".{pdf_path.name}.",
            suffix=".pdf",
            delete=False,
        ) as temporary:
            pdf_stage = Path(temporary.name)
        with NamedTemporaryFile(
            dir=csv_path.parent,
            prefix=f".{csv_path.name}.",
            suffix=".csv",
            delete=False,
        ) as temporary:
            csv_stage = Path(temporary.name)

        write_plot(result, pdf_stage)
        pdf_record = companion_artifact_record(pdf_stage)
        write_baseline(
            result,
            csv_stage,
            companion_pdf=pdf_record,
            fingerprint=fingerprint,
            producer_runtime=producer_runtime,
        )
        read_baseline(
            csv_stage,
            companion_pdf_path=pdf_stage,
            require_current=True,
        )
        if fingerprint != solver_fingerprint() or producer_runtime != producer_runtime_provenance():
            raise PhotonKickArtifactError(
                "Transient executable source/configuration or numerical runtime changed "
                "before promotion; "
                "discarding the staged pair."
            )
        os.replace(pdf_stage, pdf_path)
        pdf_stage = None
        os.replace(csv_stage, csv_path)
        csv_stage = None
        return csv_path, pdf_path
    finally:
        if csv_stage is not None:
            csv_stage.unlink(missing_ok=True)
        if pdf_stage is not None:
            pdf_stage.unlink(missing_ok=True)


def generate_baseline() -> tuple[Path, Path]:
    import matplotlib

    # Fix the plotting/runtime contract before provenance is captured.  Calling
    # ``matplotlib.use("Agg")`` only during post-solve staging would otherwise
    # look like an unexplained runtime change on interactive installations.
    matplotlib.use("Agg")
    print("qpsim transient-driver demo — PB-photon kick response")
    print(f"  Δ₀={DELTA_0} μeV, τ_0={TAU_0} ns, T_B={T_BATH} K")
    print(f"  Drive: ω_PB={OMEGA_PB:.2f} μeV, n̄_PB={N_BAR_PB:.0e}, c_phot_PB={C_PHOT_PB:.0e}")
    print(f"  dt={DT} ns, total_time={TOTAL_TIME} ns, snapshot_interval={SNAPSHOT_INTERVAL} ns")
    fingerprint = solver_fingerprint()
    producer_runtime = producer_runtime_provenance()
    result = run()
    print(f"  n_snapshots = {result.snapshot_times.size}")
    print(
        f"  x_qp: {result.x_qp_snapshots[0]:.3e} (t=0) → "
        f"{result.x_qp_snapshots[-1]:.3e} (t={TOTAL_TIME:.0f} ns)"
    )
    print(f"  x_qp_steady_state = {result.x_qp_steady_state:.3e}")
    csv_path, pdf_path = publish_baseline_pair(
        result,
        fingerprint=fingerprint,
        producer_runtime=producer_runtime,
    )
    print(f"  Baseline CSV: {csv_path}")
    print(f"  PDF plot:     {pdf_path}")
    return csv_path, pdf_path


if __name__ == "__main__":
    generate_baseline()
