"""Layer-1–5 validation per New Framework Plan §6.

Structure:
- tier_reductions/ — Layer 2: T1→T2, T2→T3, T3(LEGACY)→frozen
- fischer_2023/   — F23 paper-topology regressions and characterization
- fischer_2024/   — F24 Fig. 5–8 pair-breaking photon tests
- analytic/       — Layer 1: detailed balance, MB thermal, USADEL→∇²
- baselines/      — pinned CSVs generated by these modules (see its README)
"""
