"""Validation suites.

Structure:
- fischer_2023/   — F23 paper-topology regressions and characterization
- fischer_2024/   — F24 Fig. 5–8 pair-breaking photon tests
- analytic/       — detailed balance, MB thermal, USADEL→∇²
- baselines/      — pinned CSVs generated by these modules (see its README)
"""
