"""Validation suites.

Structure:
- fischer_2023/         — F23 paper-topology regressions and characterization
- fischer_2024/         — F24 Fig. 5–8 pair-breaking photon tests
- analytic/             — detailed balance (aggregate and per channel), MB
                          thermal, gap-equation equilibrium, the driven phonon
                          fixed point, and closed-form eigenmodes of the
                          spatial core on a rectangle and an annulus
- diffusion_operators/  — (p, q) operator-family benchmarks, incl. the
                          uniform-Δ D_eff reduction (A1 against the
                          diagnostics), DOS-gradient drift, the
                          Kupriyanov-Lukichev trap and self-consistent feedback
- transient/            — photon-kick response of f(E, t) on one cell
- reference_models/     — clean-room reference models that never import qpsim
- baselines/            — pinned CSVs generated by these modules (see its README)
- paper_data/           — coordinates extracted from publication assets, with
                          the oracle / comparison-spec / score contracts over
                          them (see its README)
"""
